2004-02-20 18:47:1  |Darts          |1  |0|15  |default admin       |Дартс                         |
04-02-2014 18:54  |Darts          |0.00  |100|10  |default admin       |Дартс                         |
04-02-2014 19:38  |Darts          |0.00  |100|2  |default admin       |Дартс                         |
04-02-2014 19:45  |Darts          |0.00  |100|1  |default admin       |Дартс                         |
04-02-2014 19:50  |MiniSnooker    |0.26  |50|5  |default admin       |Маса 13 - Малък Снукър        |
04-02-2014 20:28  |Darts          |0.00  |100|0  |default admin       |Дартс                         |
